Урок 2. Матрицы и матричные операции

Практическое задание
Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

1. Установите, какие произведения матриц 𝐴𝐵 и 𝐵𝐴 определены, и найдите размерности полученных матриц:

а) 𝐴 — матрица 4×2, 𝐵 — матрица 4×2;

б) 𝐴 — матрица 2×5, 𝐵 — матрица 5×3;

в) 𝐴 — матрица 8×3, 𝐵 — матрица 3×8;

г) 𝐴 — квадратная матрица 4×4, 𝐵 — квадратная матрица 4×4.

Решение

а) умножать нельзя
б) умножать можно, 2×3
в) умножать можно, 8×8
б) умножать можно, 4×4

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


In [19]:
import numpy as np

In [20]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [21]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}')
print(f'Матрица B\n{b}')
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [22]:
a = np.array([[1, 7], [3, -6]])
k = 3

print(f'Матрица А\n{a}\n')
print(f'Матрица 3*А\n{k*a}')

Матрица А
[[ 1  7]
 [ 3 -6]]

Матрица 3*А
[[  3  21]
 [  9 -18]]


In [23]:
b = np.array([[0, 5], [2, -1]])
k = 2

print(f'Матрица B\n{b}\n')
print(f'Матрица 2*B\n{k*b}')

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица 2*B
[[ 0 10]
 [ 4 -2]]


In [24]:
c = np.array([[2, -4], [1, 1]])
k = 4

print(f'Матрица C\n{c}\n')
print(f'Матрица 4*C\n{k*c}')

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 4*C
[[  8 -16]
 [  4   4]]


In [25]:
a = np.array([[3, 21], [9, -18]])
b = np.array([[0, 10], [4, -2]])
c = np.array([[8, -16], [4, 4]])

print(f'Матрица 3A\n{a}\n')
print(f'Матрица 2B\n{b}\n')
print(f'Матрица 4C\n{c}\n')
print(f'Матрица D = 3A - 2B + 4C\n{a - b + c}')

Матрица 3A
[[  3  21]
 [  9 -18]]

Матрица 2B
[[ 0 10]
 [ 4 -2]]

Матрица 4C
[[  8 -16]
 [  4   4]]

Матрица D = 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

In [26]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


In [27]:
a = np.array([[4, 1], [5, -2], [2, 3]])
b = np.array([[4, 5, 2], [1, -2, 3]])

print(f'Матрица A\n{a}')
print(f'Матрица AТ\n{b}')
print(f'Матрица AAТ\n{np.dot(a, b)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица AТ
[[ 4  5  2]
 [ 1 -2  3]]
Матрица AAТ
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [28]:
a = np.array([[4, 5, 2], [1, -2, 3]])
b = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица AТ\n{a}')
print(f'Матрица A\n{b}')
print(f'Матрица AТА\n{np.dot(a, b)}')

Матрица AТ
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица AТА
[[45  0]
 [ 0 14]]


## Практическое задание



__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [2]:
import numpy as np

а) 

sin(x^2) + cos(x^2) = 1

б)

In [34]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


в)

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


а) $det(A^{2})$ = 16

б) $det(A^{T})$ = 4

в) $det(2A)$ = 8

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [3]:
b = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


так как $det(A)$ = 0 - матрица вырождена

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а)

In [4]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [5]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
v = [2, 3, 5, 6]

a = np.array([x, y, z, v])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
